title: eXiga thoughts
email: anton.kostenich@hotmail.com
description: >-
  Just my thoughts about IT, programming and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AntonKostenich
github_username:  eXiga

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile